# Generated by Django 4.1.2 on 2022-10-12 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='date',
            field=models.DateField(default='1970-10-10'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='block',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='block',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
