# Generated by Django 4.1.2 on 2022-10-31 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_event_all_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='all_day',
        ),
        migrations.AddField(
            model_name='event',
            name='allDay',
            field=models.BooleanField(default=True),
        ),
    ]
